// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: market_data.proto

#include "market_data.pb.h"
#include "market_data.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace marketdata {

static const char* MarketDataService_method_names[] = {
  "/marketdata.MarketDataService/Subscribe",
};

std::unique_ptr< MarketDataService::Stub> MarketDataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MarketDataService::Stub> stub(new MarketDataService::Stub(channel, options));
  return stub;
}

MarketDataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Subscribe_(MarketDataService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>* MarketDataService::Stub::SubscribeRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>::Create(channel_.get(), rpcmethod_Subscribe_, context);
}

void MarketDataService::Stub::async::Subscribe(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::marketdata::SubscriptionRequest,::marketdata::MarketDataUpdate>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::marketdata::SubscriptionRequest,::marketdata::MarketDataUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>* MarketDataService::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>* MarketDataService::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, false, nullptr);
}

MarketDataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< MarketDataService::Service, ::marketdata::SubscriptionRequest, ::marketdata::MarketDataUpdate>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::marketdata::MarketDataUpdate,
             ::marketdata::SubscriptionRequest>* stream) {
               return service->Subscribe(ctx, stream);
             }, this)));
}

MarketDataService::Service::~Service() {
}

::grpc::Status MarketDataService::Service::Subscribe(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::marketdata::MarketDataUpdate, ::marketdata::SubscriptionRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace marketdata

