// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: market_data.proto
// Protobuf C++ Version: 5.29.3

#include "market_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace marketdata {

inline constexpr SubscriptionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : instrument_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_{static_cast< ::marketdata::SubscriptionRequest_Action >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SubscriptionRequest::SubscriptionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SubscriptionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubscriptionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubscriptionRequestDefaultTypeInternal() {}
  union {
    SubscriptionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubscriptionRequestDefaultTypeInternal _SubscriptionRequest_default_instance_;

inline constexpr PriceLevel::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : price_{0},
        quantity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PriceLevel::PriceLevel(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PriceLevelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PriceLevelDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PriceLevelDefaultTypeInternal() {}
  union {
    PriceLevel _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PriceLevelDefaultTypeInternal _PriceLevel_default_instance_;

inline constexpr OrderBookSnapshot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : bids_{},
        asks_{},
        instrument_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OrderBookSnapshot::OrderBookSnapshot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OrderBookSnapshotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OrderBookSnapshotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OrderBookSnapshotDefaultTypeInternal() {}
  union {
    OrderBookSnapshot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OrderBookSnapshotDefaultTypeInternal _OrderBookSnapshot_default_instance_;

inline constexpr OrderBookIncrementalUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : bid_updates_{},
        ask_updates_{},
        instrument_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OrderBookIncrementalUpdate::OrderBookIncrementalUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OrderBookIncrementalUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OrderBookIncrementalUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OrderBookIncrementalUpdateDefaultTypeInternal() {}
  union {
    OrderBookIncrementalUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OrderBookIncrementalUpdateDefaultTypeInternal _OrderBookIncrementalUpdate_default_instance_;

inline constexpr MarketDataUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : update_type_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MarketDataUpdate::MarketDataUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MarketDataUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MarketDataUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MarketDataUpdateDefaultTypeInternal() {}
  union {
    MarketDataUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MarketDataUpdateDefaultTypeInternal _MarketDataUpdate_default_instance_;
}  // namespace marketdata
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_market_5fdata_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_market_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_market_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::SubscriptionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::SubscriptionRequest, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::marketdata::SubscriptionRequest, _impl_.instrument_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::MarketDataUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::marketdata::MarketDataUpdate, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::marketdata::MarketDataUpdate, _impl_.update_type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookSnapshot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookSnapshot, _impl_.instrument_id_),
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookSnapshot, _impl_.bids_),
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookSnapshot, _impl_.asks_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookIncrementalUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookIncrementalUpdate, _impl_.instrument_id_),
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookIncrementalUpdate, _impl_.bid_updates_),
        PROTOBUF_FIELD_OFFSET(::marketdata::OrderBookIncrementalUpdate, _impl_.ask_updates_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceLevel, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceLevel, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::marketdata::PriceLevel, _impl_.quantity_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::marketdata::SubscriptionRequest)},
        {10, -1, -1, sizeof(::marketdata::MarketDataUpdate)},
        {21, -1, -1, sizeof(::marketdata::OrderBookSnapshot)},
        {32, -1, -1, sizeof(::marketdata::OrderBookIncrementalUpdate)},
        {43, -1, -1, sizeof(::marketdata::PriceLevel)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::marketdata::_SubscriptionRequest_default_instance_._instance,
    &::marketdata::_MarketDataUpdate_default_instance_._instance,
    &::marketdata::_OrderBookSnapshot_default_instance_._instance,
    &::marketdata::_OrderBookIncrementalUpdate_default_instance_._instance,
    &::marketdata::_PriceLevel_default_instance_._instance,
};
const char descriptor_table_protodef_market_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021market_data.proto\022\nmarketdata\"\216\001\n\023Subs"
    "criptionRequest\0226\n\006action\030\001 \001(\0162&.market"
    "data.SubscriptionRequest.Action\022\025\n\rinstr"
    "ument_id\030\002 \001(\t\"(\n\006Action\022\r\n\tSUBSCRIBE\020\000\022"
    "\017\n\013UNSUBSCRIBE\020\001\"\232\001\n\020MarketDataUpdate\0221\n"
    "\010snapshot\030\001 \001(\0132\035.marketdata.OrderBookSn"
    "apshotH\000\022D\n\022incremental_update\030\002 \001(\0132&.m"
    "arketdata.OrderBookIncrementalUpdateH\000B\r"
    "\n\013update_type\"v\n\021OrderBookSnapshot\022\025\n\rin"
    "strument_id\030\001 \001(\t\022$\n\004bids\030\002 \003(\0132\026.market"
    "data.PriceLevel\022$\n\004asks\030\003 \003(\0132\026.marketda"
    "ta.PriceLevel\"\215\001\n\032OrderBookIncrementalUp"
    "date\022\025\n\rinstrument_id\030\001 \001(\t\022+\n\013bid_updat"
    "es\030\002 \003(\0132\026.marketdata.PriceLevel\022+\n\013ask_"
    "updates\030\003 \003(\0132\026.marketdata.PriceLevel\"-\n"
    "\nPriceLevel\022\r\n\005price\030\001 \001(\001\022\020\n\010quantity\030\002"
    " \001(\0012c\n\021MarketDataService\022N\n\tSubscribe\022\037"
    ".marketdata.SubscriptionRequest\032\034.market"
    "data.MarketDataUpdate(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_market_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_market_5fdata_2eproto = {
    false,
    false,
    753,
    descriptor_table_protodef_market_5fdata_2eproto,
    "market_data.proto",
    &descriptor_table_market_5fdata_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_market_5fdata_2eproto::offsets,
    file_level_enum_descriptors_market_5fdata_2eproto,
    file_level_service_descriptors_market_5fdata_2eproto,
};
namespace marketdata {
const ::google::protobuf::EnumDescriptor* SubscriptionRequest_Action_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_market_5fdata_2eproto);
  return file_level_enum_descriptors_market_5fdata_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SubscriptionRequest_Action_internal_data_[] = {
    131072u, 0u, };
bool SubscriptionRequest_Action_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr SubscriptionRequest_Action SubscriptionRequest::SUBSCRIBE;
constexpr SubscriptionRequest_Action SubscriptionRequest::UNSUBSCRIBE;
constexpr SubscriptionRequest_Action SubscriptionRequest::Action_MIN;
constexpr SubscriptionRequest_Action SubscriptionRequest::Action_MAX;
constexpr int SubscriptionRequest::Action_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class SubscriptionRequest::_Internal {
 public:
};

SubscriptionRequest::SubscriptionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.SubscriptionRequest)
}
inline PROTOBUF_NDEBUG_INLINE SubscriptionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::SubscriptionRequest& from_msg)
      : instrument_id_(arena, from.instrument_id_),
        _cached_size_{0} {}

SubscriptionRequest::SubscriptionRequest(
    ::google::protobuf::Arena* arena,
    const SubscriptionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SubscriptionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.action_ = from._impl_.action_;

  // @@protoc_insertion_point(copy_constructor:marketdata.SubscriptionRequest)
}
inline PROTOBUF_NDEBUG_INLINE SubscriptionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : instrument_id_(arena),
        _cached_size_{0} {}

inline void SubscriptionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.action_ = {};
}
SubscriptionRequest::~SubscriptionRequest() {
  // @@protoc_insertion_point(destructor:marketdata.SubscriptionRequest)
  SharedDtor(*this);
}
inline void SubscriptionRequest::SharedDtor(MessageLite& self) {
  SubscriptionRequest& this_ = static_cast<SubscriptionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.instrument_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SubscriptionRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SubscriptionRequest(arena);
}
constexpr auto SubscriptionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SubscriptionRequest),
                                            alignof(SubscriptionRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SubscriptionRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SubscriptionRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SubscriptionRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SubscriptionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SubscriptionRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SubscriptionRequest>(), &SubscriptionRequest::ByteSizeLong,
            &SubscriptionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SubscriptionRequest, _impl_._cached_size_),
        false,
    },
    &SubscriptionRequest::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SubscriptionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 52, 2> SubscriptionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::SubscriptionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string instrument_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SubscriptionRequest, _impl_.instrument_id_)}},
    // .marketdata.SubscriptionRequest.Action action = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SubscriptionRequest, _impl_.action_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SubscriptionRequest, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .marketdata.SubscriptionRequest.Action action = 1;
    {PROTOBUF_FIELD_OFFSET(SubscriptionRequest, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string instrument_id = 2;
    {PROTOBUF_FIELD_OFFSET(SubscriptionRequest, _impl_.instrument_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\15\0\0\0\0\0"
    "marketdata.SubscriptionRequest"
    "instrument_id"
  }},
};

PROTOBUF_NOINLINE void SubscriptionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.SubscriptionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instrument_id_.ClearToEmpty();
  _impl_.action_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SubscriptionRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SubscriptionRequest& this_ = static_cast<const SubscriptionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SubscriptionRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SubscriptionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.SubscriptionRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .marketdata.SubscriptionRequest.Action action = 1;
          if (this_._internal_action() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_action(), target);
          }

          // string instrument_id = 2;
          if (!this_._internal_instrument_id().empty()) {
            const std::string& _s = this_._internal_instrument_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marketdata.SubscriptionRequest.instrument_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.SubscriptionRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SubscriptionRequest::ByteSizeLong(const MessageLite& base) {
          const SubscriptionRequest& this_ = static_cast<const SubscriptionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SubscriptionRequest::ByteSizeLong() const {
          const SubscriptionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.SubscriptionRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string instrument_id = 2;
            if (!this_._internal_instrument_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_instrument_id());
            }
            // .marketdata.SubscriptionRequest.Action action = 1;
            if (this_._internal_action() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SubscriptionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SubscriptionRequest*>(&to_msg);
  auto& from = static_cast<const SubscriptionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.SubscriptionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_instrument_id().empty()) {
    _this->_internal_set_instrument_id(from._internal_instrument_id());
  }
  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SubscriptionRequest::CopyFrom(const SubscriptionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.SubscriptionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SubscriptionRequest::InternalSwap(SubscriptionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.instrument_id_, &other->_impl_.instrument_id_, arena);
  swap(_impl_.action_, other->_impl_.action_);
}

::google::protobuf::Metadata SubscriptionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MarketDataUpdate::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::marketdata::MarketDataUpdate, _impl_._oneof_case_);
};

void MarketDataUpdate::set_allocated_snapshot(::marketdata::OrderBookSnapshot* snapshot) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_update_type();
  if (snapshot) {
    ::google::protobuf::Arena* submessage_arena = snapshot->GetArena();
    if (message_arena != submessage_arena) {
      snapshot = ::google::protobuf::internal::GetOwnedMessage(message_arena, snapshot, submessage_arena);
    }
    set_has_snapshot();
    _impl_.update_type_.snapshot_ = snapshot;
  }
  // @@protoc_insertion_point(field_set_allocated:marketdata.MarketDataUpdate.snapshot)
}
void MarketDataUpdate::set_allocated_incremental_update(::marketdata::OrderBookIncrementalUpdate* incremental_update) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_update_type();
  if (incremental_update) {
    ::google::protobuf::Arena* submessage_arena = incremental_update->GetArena();
    if (message_arena != submessage_arena) {
      incremental_update = ::google::protobuf::internal::GetOwnedMessage(message_arena, incremental_update, submessage_arena);
    }
    set_has_incremental_update();
    _impl_.update_type_.incremental_update_ = incremental_update;
  }
  // @@protoc_insertion_point(field_set_allocated:marketdata.MarketDataUpdate.incremental_update)
}
MarketDataUpdate::MarketDataUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.MarketDataUpdate)
}
inline PROTOBUF_NDEBUG_INLINE MarketDataUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::MarketDataUpdate& from_msg)
      : update_type_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

MarketDataUpdate::MarketDataUpdate(
    ::google::protobuf::Arena* arena,
    const MarketDataUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MarketDataUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (update_type_case()) {
    case UPDATE_TYPE_NOT_SET:
      break;
      case kSnapshot:
        _impl_.update_type_.snapshot_ = ::google::protobuf::Message::CopyConstruct<::marketdata::OrderBookSnapshot>(arena, *from._impl_.update_type_.snapshot_);
        break;
      case kIncrementalUpdate:
        _impl_.update_type_.incremental_update_ = ::google::protobuf::Message::CopyConstruct<::marketdata::OrderBookIncrementalUpdate>(arena, *from._impl_.update_type_.incremental_update_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:marketdata.MarketDataUpdate)
}
inline PROTOBUF_NDEBUG_INLINE MarketDataUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : update_type_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void MarketDataUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MarketDataUpdate::~MarketDataUpdate() {
  // @@protoc_insertion_point(destructor:marketdata.MarketDataUpdate)
  SharedDtor(*this);
}
inline void MarketDataUpdate::SharedDtor(MessageLite& self) {
  MarketDataUpdate& this_ = static_cast<MarketDataUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_update_type()) {
    this_.clear_update_type();
  }
  this_._impl_.~Impl_();
}

void MarketDataUpdate::clear_update_type() {
// @@protoc_insertion_point(one_of_clear_start:marketdata.MarketDataUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (update_type_case()) {
    case kSnapshot: {
      if (GetArena() == nullptr) {
        delete _impl_.update_type_.snapshot_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.update_type_.snapshot_);
      }
      break;
    }
    case kIncrementalUpdate: {
      if (GetArena() == nullptr) {
        delete _impl_.update_type_.incremental_update_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.update_type_.incremental_update_);
      }
      break;
    }
    case UPDATE_TYPE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = UPDATE_TYPE_NOT_SET;
}


inline void* MarketDataUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MarketDataUpdate(arena);
}
constexpr auto MarketDataUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MarketDataUpdate),
                                            alignof(MarketDataUpdate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MarketDataUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MarketDataUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MarketDataUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MarketDataUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MarketDataUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MarketDataUpdate>(), &MarketDataUpdate::ByteSizeLong,
            &MarketDataUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MarketDataUpdate, _impl_._cached_size_),
        false,
    },
    &MarketDataUpdate::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MarketDataUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> MarketDataUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::MarketDataUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .marketdata.OrderBookSnapshot snapshot = 1;
    {PROTOBUF_FIELD_OFFSET(MarketDataUpdate, _impl_.update_type_.snapshot_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .marketdata.OrderBookIncrementalUpdate incremental_update = 2;
    {PROTOBUF_FIELD_OFFSET(MarketDataUpdate, _impl_.update_type_.incremental_update_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::marketdata::OrderBookSnapshot>()},
    {::_pbi::TcParser::GetTable<::marketdata::OrderBookIncrementalUpdate>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MarketDataUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.MarketDataUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_update_type();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MarketDataUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MarketDataUpdate& this_ = static_cast<const MarketDataUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MarketDataUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MarketDataUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.MarketDataUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.update_type_case()) {
            case kSnapshot: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.update_type_.snapshot_, this_._impl_.update_type_.snapshot_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kIncrementalUpdate: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.update_type_.incremental_update_, this_._impl_.update_type_.incremental_update_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.MarketDataUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MarketDataUpdate::ByteSizeLong(const MessageLite& base) {
          const MarketDataUpdate& this_ = static_cast<const MarketDataUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MarketDataUpdate::ByteSizeLong() const {
          const MarketDataUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.MarketDataUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.update_type_case()) {
            // .marketdata.OrderBookSnapshot snapshot = 1;
            case kSnapshot: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.update_type_.snapshot_);
              break;
            }
            // .marketdata.OrderBookIncrementalUpdate incremental_update = 2;
            case kIncrementalUpdate: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.update_type_.incremental_update_);
              break;
            }
            case UPDATE_TYPE_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MarketDataUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MarketDataUpdate*>(&to_msg);
  auto& from = static_cast<const MarketDataUpdate&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.MarketDataUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_update_type();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSnapshot: {
        if (oneof_needs_init) {
          _this->_impl_.update_type_.snapshot_ =
              ::google::protobuf::Message::CopyConstruct<::marketdata::OrderBookSnapshot>(arena, *from._impl_.update_type_.snapshot_);
        } else {
          _this->_impl_.update_type_.snapshot_->MergeFrom(from._internal_snapshot());
        }
        break;
      }
      case kIncrementalUpdate: {
        if (oneof_needs_init) {
          _this->_impl_.update_type_.incremental_update_ =
              ::google::protobuf::Message::CopyConstruct<::marketdata::OrderBookIncrementalUpdate>(arena, *from._impl_.update_type_.incremental_update_);
        } else {
          _this->_impl_.update_type_.incremental_update_->MergeFrom(from._internal_incremental_update());
        }
        break;
      }
      case UPDATE_TYPE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MarketDataUpdate::CopyFrom(const MarketDataUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.MarketDataUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MarketDataUpdate::InternalSwap(MarketDataUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.update_type_, other->_impl_.update_type_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MarketDataUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OrderBookSnapshot::_Internal {
 public:
};

OrderBookSnapshot::OrderBookSnapshot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.OrderBookSnapshot)
}
inline PROTOBUF_NDEBUG_INLINE OrderBookSnapshot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::OrderBookSnapshot& from_msg)
      : bids_{visibility, arena, from.bids_},
        asks_{visibility, arena, from.asks_},
        instrument_id_(arena, from.instrument_id_),
        _cached_size_{0} {}

OrderBookSnapshot::OrderBookSnapshot(
    ::google::protobuf::Arena* arena,
    const OrderBookSnapshot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OrderBookSnapshot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:marketdata.OrderBookSnapshot)
}
inline PROTOBUF_NDEBUG_INLINE OrderBookSnapshot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : bids_{visibility, arena},
        asks_{visibility, arena},
        instrument_id_(arena),
        _cached_size_{0} {}

inline void OrderBookSnapshot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OrderBookSnapshot::~OrderBookSnapshot() {
  // @@protoc_insertion_point(destructor:marketdata.OrderBookSnapshot)
  SharedDtor(*this);
}
inline void OrderBookSnapshot::SharedDtor(MessageLite& self) {
  OrderBookSnapshot& this_ = static_cast<OrderBookSnapshot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.instrument_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* OrderBookSnapshot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OrderBookSnapshot(arena);
}
constexpr auto OrderBookSnapshot::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.bids_) +
          decltype(OrderBookSnapshot::_impl_.bids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.asks_) +
          decltype(OrderBookSnapshot::_impl_.asks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(OrderBookSnapshot), alignof(OrderBookSnapshot), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&OrderBookSnapshot::PlacementNew_,
                                 sizeof(OrderBookSnapshot),
                                 alignof(OrderBookSnapshot));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OrderBookSnapshot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OrderBookSnapshot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OrderBookSnapshot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OrderBookSnapshot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OrderBookSnapshot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OrderBookSnapshot>(), &OrderBookSnapshot::ByteSizeLong,
            &OrderBookSnapshot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_._cached_size_),
        false,
    },
    &OrderBookSnapshot::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OrderBookSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 50, 2> OrderBookSnapshot::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::OrderBookSnapshot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string instrument_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.instrument_id_)}},
    // repeated .marketdata.PriceLevel bids = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.bids_)}},
    // repeated .marketdata.PriceLevel asks = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 1, PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.asks_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string instrument_id = 1;
    {PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.instrument_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .marketdata.PriceLevel bids = 2;
    {PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.bids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .marketdata.PriceLevel asks = 3;
    {PROTOBUF_FIELD_OFFSET(OrderBookSnapshot, _impl_.asks_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::marketdata::PriceLevel>()},
    {::_pbi::TcParser::GetTable<::marketdata::PriceLevel>()},
  }}, {{
    "\34\15\0\0\0\0\0\0"
    "marketdata.OrderBookSnapshot"
    "instrument_id"
  }},
};

PROTOBUF_NOINLINE void OrderBookSnapshot::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.OrderBookSnapshot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bids_.Clear();
  _impl_.asks_.Clear();
  _impl_.instrument_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OrderBookSnapshot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OrderBookSnapshot& this_ = static_cast<const OrderBookSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OrderBookSnapshot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OrderBookSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.OrderBookSnapshot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string instrument_id = 1;
          if (!this_._internal_instrument_id().empty()) {
            const std::string& _s = this_._internal_instrument_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marketdata.OrderBookSnapshot.instrument_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .marketdata.PriceLevel bids = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_bids_size());
               i < n; i++) {
            const auto& repfield = this_._internal_bids().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .marketdata.PriceLevel asks = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_asks_size());
               i < n; i++) {
            const auto& repfield = this_._internal_asks().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.OrderBookSnapshot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OrderBookSnapshot::ByteSizeLong(const MessageLite& base) {
          const OrderBookSnapshot& this_ = static_cast<const OrderBookSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OrderBookSnapshot::ByteSizeLong() const {
          const OrderBookSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.OrderBookSnapshot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .marketdata.PriceLevel bids = 2;
            {
              total_size += 1UL * this_._internal_bids_size();
              for (const auto& msg : this_._internal_bids()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .marketdata.PriceLevel asks = 3;
            {
              total_size += 1UL * this_._internal_asks_size();
              for (const auto& msg : this_._internal_asks()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string instrument_id = 1;
            if (!this_._internal_instrument_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_instrument_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OrderBookSnapshot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OrderBookSnapshot*>(&to_msg);
  auto& from = static_cast<const OrderBookSnapshot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.OrderBookSnapshot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_bids()->MergeFrom(
      from._internal_bids());
  _this->_internal_mutable_asks()->MergeFrom(
      from._internal_asks());
  if (!from._internal_instrument_id().empty()) {
    _this->_internal_set_instrument_id(from._internal_instrument_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OrderBookSnapshot::CopyFrom(const OrderBookSnapshot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.OrderBookSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OrderBookSnapshot::InternalSwap(OrderBookSnapshot* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bids_.InternalSwap(&other->_impl_.bids_);
  _impl_.asks_.InternalSwap(&other->_impl_.asks_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.instrument_id_, &other->_impl_.instrument_id_, arena);
}

::google::protobuf::Metadata OrderBookSnapshot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OrderBookIncrementalUpdate::_Internal {
 public:
};

OrderBookIncrementalUpdate::OrderBookIncrementalUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.OrderBookIncrementalUpdate)
}
inline PROTOBUF_NDEBUG_INLINE OrderBookIncrementalUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marketdata::OrderBookIncrementalUpdate& from_msg)
      : bid_updates_{visibility, arena, from.bid_updates_},
        ask_updates_{visibility, arena, from.ask_updates_},
        instrument_id_(arena, from.instrument_id_),
        _cached_size_{0} {}

OrderBookIncrementalUpdate::OrderBookIncrementalUpdate(
    ::google::protobuf::Arena* arena,
    const OrderBookIncrementalUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OrderBookIncrementalUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:marketdata.OrderBookIncrementalUpdate)
}
inline PROTOBUF_NDEBUG_INLINE OrderBookIncrementalUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : bid_updates_{visibility, arena},
        ask_updates_{visibility, arena},
        instrument_id_(arena),
        _cached_size_{0} {}

inline void OrderBookIncrementalUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OrderBookIncrementalUpdate::~OrderBookIncrementalUpdate() {
  // @@protoc_insertion_point(destructor:marketdata.OrderBookIncrementalUpdate)
  SharedDtor(*this);
}
inline void OrderBookIncrementalUpdate::SharedDtor(MessageLite& self) {
  OrderBookIncrementalUpdate& this_ = static_cast<OrderBookIncrementalUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.instrument_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* OrderBookIncrementalUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OrderBookIncrementalUpdate(arena);
}
constexpr auto OrderBookIncrementalUpdate::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.bid_updates_) +
          decltype(OrderBookIncrementalUpdate::_impl_.bid_updates_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.ask_updates_) +
          decltype(OrderBookIncrementalUpdate::_impl_.ask_updates_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(OrderBookIncrementalUpdate), alignof(OrderBookIncrementalUpdate), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&OrderBookIncrementalUpdate::PlacementNew_,
                                 sizeof(OrderBookIncrementalUpdate),
                                 alignof(OrderBookIncrementalUpdate));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OrderBookIncrementalUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OrderBookIncrementalUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OrderBookIncrementalUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OrderBookIncrementalUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OrderBookIncrementalUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OrderBookIncrementalUpdate>(), &OrderBookIncrementalUpdate::ByteSizeLong,
            &OrderBookIncrementalUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_._cached_size_),
        false,
    },
    &OrderBookIncrementalUpdate::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OrderBookIncrementalUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 59, 2> OrderBookIncrementalUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::OrderBookIncrementalUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string instrument_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.instrument_id_)}},
    // repeated .marketdata.PriceLevel bid_updates = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.bid_updates_)}},
    // repeated .marketdata.PriceLevel ask_updates = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 1, PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.ask_updates_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string instrument_id = 1;
    {PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.instrument_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .marketdata.PriceLevel bid_updates = 2;
    {PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.bid_updates_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .marketdata.PriceLevel ask_updates = 3;
    {PROTOBUF_FIELD_OFFSET(OrderBookIncrementalUpdate, _impl_.ask_updates_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::marketdata::PriceLevel>()},
    {::_pbi::TcParser::GetTable<::marketdata::PriceLevel>()},
  }}, {{
    "\45\15\0\0\0\0\0\0"
    "marketdata.OrderBookIncrementalUpdate"
    "instrument_id"
  }},
};

PROTOBUF_NOINLINE void OrderBookIncrementalUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.OrderBookIncrementalUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bid_updates_.Clear();
  _impl_.ask_updates_.Clear();
  _impl_.instrument_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OrderBookIncrementalUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OrderBookIncrementalUpdate& this_ = static_cast<const OrderBookIncrementalUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OrderBookIncrementalUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OrderBookIncrementalUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.OrderBookIncrementalUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string instrument_id = 1;
          if (!this_._internal_instrument_id().empty()) {
            const std::string& _s = this_._internal_instrument_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marketdata.OrderBookIncrementalUpdate.instrument_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .marketdata.PriceLevel bid_updates = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_bid_updates_size());
               i < n; i++) {
            const auto& repfield = this_._internal_bid_updates().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .marketdata.PriceLevel ask_updates = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_ask_updates_size());
               i < n; i++) {
            const auto& repfield = this_._internal_ask_updates().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.OrderBookIncrementalUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OrderBookIncrementalUpdate::ByteSizeLong(const MessageLite& base) {
          const OrderBookIncrementalUpdate& this_ = static_cast<const OrderBookIncrementalUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OrderBookIncrementalUpdate::ByteSizeLong() const {
          const OrderBookIncrementalUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.OrderBookIncrementalUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .marketdata.PriceLevel bid_updates = 2;
            {
              total_size += 1UL * this_._internal_bid_updates_size();
              for (const auto& msg : this_._internal_bid_updates()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .marketdata.PriceLevel ask_updates = 3;
            {
              total_size += 1UL * this_._internal_ask_updates_size();
              for (const auto& msg : this_._internal_ask_updates()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string instrument_id = 1;
            if (!this_._internal_instrument_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_instrument_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OrderBookIncrementalUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OrderBookIncrementalUpdate*>(&to_msg);
  auto& from = static_cast<const OrderBookIncrementalUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.OrderBookIncrementalUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_bid_updates()->MergeFrom(
      from._internal_bid_updates());
  _this->_internal_mutable_ask_updates()->MergeFrom(
      from._internal_ask_updates());
  if (!from._internal_instrument_id().empty()) {
    _this->_internal_set_instrument_id(from._internal_instrument_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OrderBookIncrementalUpdate::CopyFrom(const OrderBookIncrementalUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.OrderBookIncrementalUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OrderBookIncrementalUpdate::InternalSwap(OrderBookIncrementalUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bid_updates_.InternalSwap(&other->_impl_.bid_updates_);
  _impl_.ask_updates_.InternalSwap(&other->_impl_.ask_updates_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.instrument_id_, &other->_impl_.instrument_id_, arena);
}

::google::protobuf::Metadata OrderBookIncrementalUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PriceLevel::_Internal {
 public:
};

PriceLevel::PriceLevel(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marketdata.PriceLevel)
}
PriceLevel::PriceLevel(
    ::google::protobuf::Arena* arena, const PriceLevel& from)
    : PriceLevel(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PriceLevel::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PriceLevel::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, quantity_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::quantity_));
}
PriceLevel::~PriceLevel() {
  // @@protoc_insertion_point(destructor:marketdata.PriceLevel)
  SharedDtor(*this);
}
inline void PriceLevel::SharedDtor(MessageLite& self) {
  PriceLevel& this_ = static_cast<PriceLevel&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PriceLevel::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PriceLevel(arena);
}
constexpr auto PriceLevel::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PriceLevel),
                                            alignof(PriceLevel));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PriceLevel::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PriceLevel_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PriceLevel::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PriceLevel>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PriceLevel::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PriceLevel>(), &PriceLevel::ByteSizeLong,
            &PriceLevel::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_._cached_size_),
        false,
    },
    &PriceLevel::kDescriptorMethods,
    &descriptor_table_market_5fdata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PriceLevel::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> PriceLevel::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marketdata::PriceLevel>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double quantity = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.quantity_)}},
    // double price = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.price_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double price = 1;
    {PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double quantity = 2;
    {PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.quantity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void PriceLevel::Clear() {
// @@protoc_insertion_point(message_clear_start:marketdata.PriceLevel)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.quantity_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.quantity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PriceLevel::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PriceLevel& this_ = static_cast<const PriceLevel&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PriceLevel::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PriceLevel& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marketdata.PriceLevel)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double price = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_price(), target);
          }

          // double quantity = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_quantity(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marketdata.PriceLevel)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PriceLevel::ByteSizeLong(const MessageLite& base) {
          const PriceLevel& this_ = static_cast<const PriceLevel&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PriceLevel::ByteSizeLong() const {
          const PriceLevel& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marketdata.PriceLevel)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double price = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_price()) != 0) {
              total_size += 9;
            }
            // double quantity = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_quantity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PriceLevel::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PriceLevel*>(&to_msg);
  auto& from = static_cast<const PriceLevel&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marketdata.PriceLevel)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_price()) != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_quantity()) != 0) {
    _this->_impl_.quantity_ = from._impl_.quantity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PriceLevel::CopyFrom(const PriceLevel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marketdata.PriceLevel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PriceLevel::InternalSwap(PriceLevel* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.quantity_)
      + sizeof(PriceLevel::_impl_.quantity_)
      - PROTOBUF_FIELD_OFFSET(PriceLevel, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata PriceLevel::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace marketdata
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_market_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
